language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - hhvm
  
matrix:
    include:
        - php: 5.6
          env: SEND_COVERAGE=true
          
env:
    global:
        - SEND_COVERAGE=false
        - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install
  - mkdir build
  - mkdir -p build/logs
  - mkdir -p test/logs
  
script: 
  - phpunit -v 

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.xml; fi
