<?php

namespace Soluble\Schema;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-05 at 14:40:25.
 */
class MetadataTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Metadata
     */
    protected $mysqli_meta;

    /**
     * @var Metadata
     */    
    protected $pdo_meta;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->mysqli_meta = new Metadata(\SolubleTestFactories::getDbConnection('mysqli'));
        $this->pdo_meta = new Metadata(\SolubleTestFactories::getDbConnection('pdo:mysql'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetSource()
    {
        $source = $this->mysqli_meta->getSource();
        $this->assertInstanceOf('Soluble\Schema\Source\AbstractSource', $source);
        
        $source = $this->pdo_meta->getSource();
        $this->assertInstanceOf('Soluble\Schema\Source\AbstractSource', $source);
        
    }

    public function testGetConnection()
    {
        $connection = $this->mysqli_meta->getConnection();
        $this->assertInstanceOf('mysqli', $connection);
        
        $connection = $this->pdo_meta->getConnection();
        $this->assertInstanceOf('PDO', $connection);
        
    }


    public function testConstructThrowsUnsupportedDriverException()
    {
        $this->setExpectedException('Soluble\Schema\Exception\UnsupportedDriverException');

        $connection = new \PDO('sqlite::memory:');

        $metadata = new Metadata($connection);
    }
}
