<?php

namespace Soluble\Schema\Column;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-04 at 13:55:32.
 */
class TypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Type
     */
    protected $type;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }


    public function testCreateColumnDefinitionThrowsUnsupportedDatatypeException()
    {
        $this->setExpectedException('Soluble\Schema\Column\Exception\UnsupportedDatatypeException');
        $type = Type::createColumnDefinition('NOTAVALIDTYPE', 'cool');
    }
}
