<?php

namespace Soluble\Schema\Source\Mysql;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-04 at 16:46:00.
 */
class MysqlConnectionAdapterMysqliTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var MysqlConnectionAdapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = new MysqlConnectionAdapter(\SolubleTestFactories::getDbConnection('mysqli'));
    }

    public function testGetCurrentSchema()
    {
        $current = $this->adapter->getCurrentSchema();
        $this->assertEquals(\SolubleTestFactories::getDatabaseName('pdo:mysql'), $current);
    }

}
